import { mkdir, writeFile, readFile, readdir, rename } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Store, RunContext, RunSummary } from "../core/types.js";

/**
 * The default persistence: one JSON file per run. Zero dependencies, and the
 * whole point of the harness — a checkpoint after every step means "resume from
 * exactly where it died". Swap in SQLite/Redis by implementing the same Store.
 */
export class FileStore implements Store {
  constructor(private readonly dir = "runs") {}

  private async ensureDir(): Promise<void> {
    if (existsSync(this.dir)) return;
    await mkdir(this.dir, { recursive: true });
    // A checkpoint carries the run's entire history — including whatever the
    // tools read out of the user's files. Make the directory we just created
    // ignore itself, so running an agent inside a repo can't quietly stage it
    // for commit. Only ever written for a directory we create; an existing one
    // is left exactly as the user set it up.
    await writeFile(join(this.dir, ".gitignore"), "*\n", "utf8").catch(() => {});
  }

  private path(runId: string): string {
    // runId is generated by us (no path separators), but be defensive anyway.
    return join(this.dir, `${runId.replace(/[^\w.-]/g, "_")}.json`);
  }

  async save(ctx: RunContext): Promise<void> {
    await this.ensureDir();
    const file = this.path(ctx.runId);
    const tmp = `${file}.tmp`;
    // Write-then-rename so a crash mid-write never corrupts the last good checkpoint.
    await writeFile(tmp, JSON.stringify(ctx, null, 2), "utf8");
    await rename(tmp, file);
  }

  async load(runId: string): Promise<RunContext | null> {
    const file = this.path(runId);
    if (!existsSync(file)) return null;
    try {
      return JSON.parse(await readFile(file, "utf8")) as RunContext;
    } catch {
      return null;
    }
  }

  async list(): Promise<RunSummary[]> {
    if (!existsSync(this.dir)) return [];
    const files = (await readdir(this.dir)).filter((f) => f.endsWith(".json"));
    const out: RunSummary[] = [];
    for (const f of files) {
      try {
        const ctx = JSON.parse(await readFile(join(this.dir, f), "utf8")) as RunContext;
        out.push({
          runId: ctx.runId,
          goal: ctx.goal.description,
          planStatus: ctx.plan.status,
          steps: ctx.plan.steps.length,
          updatedAt: ctx.updatedAt,
        });
      } catch {
        // skip unreadable/partial files
      }
    }
    return out.sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1));
  }
}

/** An in-memory store — handy for tests and ephemeral runs. */
export class MemoryStore implements Store {
  private map = new Map<string, string>();
  async save(ctx: RunContext): Promise<void> {
    this.map.set(ctx.runId, JSON.stringify(ctx));
  }
  async load(runId: string): Promise<RunContext | null> {
    const raw = this.map.get(runId);
    return raw ? (JSON.parse(raw) as RunContext) : null;
  }
  async list(): Promise<RunSummary[]> {
    return [...this.map.values()].map((raw) => {
      const ctx = JSON.parse(raw) as RunContext;
      return { runId: ctx.runId, goal: ctx.goal.description, planStatus: ctx.plan.status, steps: ctx.plan.steps.length, updatedAt: ctx.updatedAt };
    });
  }
}
